# Site settings
title: life is a fuxking movie
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'lindx'
  email: 1195506685@qq.com
  twitter_username: lindx
#  facebook_username: joshgerdes
  github_username:  linaotian-vv
  linkedin_username:  lindx
  meetup_name: lindx

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
